### ISSUE TITLE
Comparison to html5tagger

### ISSUE THREAD

**Issue by legout** [tlonny/pdoo#1]
Hi @tlonny 

I´m curious, how your lib compares to html5tagger.

Thanks
legout

**Comment by tlonny** [comment]
Hi thanks for reaching out!

I think the biggest difference is the CSS abstraction I've implemented. With `pdoo` you can easily create parameterized/dynamic and re-usable styles. I don't believe such a facility exists with `html5tagger`.

That being said, I'm sure `html5tagger` has had a lot more time put into it and thus will probably be a "safer bet" if you're looking at using something like this in production (also check out `dominate` as an alternative). 

I'm very happily using `pdoo` on my personal websites: https://lonny.io and https://dreamlink.lonny.io, but I'm sure there are bugs lurking that need to be fixed. That being said, if you'd like to use it - please go ahead and I'll endeavor to fix any bugs you find ASAP! :-)

**Comment by legout** [comment]
Thanks for your fast response. 👍 

Indeed I am currently searching pythonic alternatives to classic template engines like jinja or mako.
I´ll give pdoo definitly a try!

**Comment by legout** [comment]
This is what i´ve found so far:

https://github.com/stars/legout/lists/py-html
